# Generated by Django 2.0.7 on 2018-07-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180730_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='creater',
            new_name='creator',
        ),
    ]
